"use client";
import Header from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import ThemeProvider, { useThemeContext } from "@/hooks/useTheme";
import { useEffect } from "react";

const poppins = Poppins({
	weight: ["200", "300", "400", "500", "600", "700"],
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Deepak Yadav",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className="dark text-sm sm:text-base">
			<body
				className={`text-black tracking-wide bg-zinc-100 dark:text-white dark:bg-zinc-950`}
			>
				<div className="max-w-4xl mx-auto my-16 px-7">
					<ThemeProvider>
						<Header />
						{children}
					</ThemeProvider>
				</div>
			</body>
		</html>
	);
}
